export const ItemsPackage = [
  {
    id: 1,
    title: "Blog Site",
    images: [
      {
        original: "./blog ss1.png",
        thumbnail: "./blog ss1.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./blog ss2.png",
        thumbnail: "./blog ss2.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./blog ss3.png",
        thumbnail: "./blog ss3.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./blog ss4.png",
        thumbnail: "./blog ss4.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./blog ss5.png",
        thumbnail: "./blog ss5.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./blog ss6.png",
        thumbnail: "./blog ss6.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./blog ss7.png",
        thumbnail: "./blog ss7.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./blog ss8.png",
        thumbnail: "./blog ss8.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./blog ss9.png",
        thumbnail: "./blog ss9.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
    ],
    desc: "A blog site built in React, SCSS, MySQL and Express, used JSONWebToken for authorizing users, ReactQuill to let the user use bold, italic, bullets etc",
    ghlink: "https://github.com/Ahmad-Shawish/blog",
    tunnel: "https://sqb9npfb-3000.euw.devtunnels.ms/",
  }
];

export const ItemsVanila = [
  {
    id: 1,
    title: "Blog Site",
    images: {
      img1: "./blog ss1.png",
      img2: "./blog ss2.png",
      img3: "./blog ss3.png",
      img4: "./blog ss4.png",
      img5: "./blog ss5.png",
      img6: "./blog ss6.png",
      img7: "./blog ss7.png",
      img8: "./blog ss8.png",
      img9: "./blog ss9.png",
    },
    desc: "A blog site built in React, SCSS, MySQL and Express, used JSONWebToken for authorizing users, ReactQuill to let the user use bold, italic, bullets etc",
    ghlink: "https://github.com/Ahmad-Shawish/blog",
    tunnel: "https://sqb9npfb-3000.euw.devtunnels.ms/",
  }
];

export const newItems = [
  {
    id: 1,
    title: "Ecommerce Shop",
    images: [
      {
        original: "./shop ss1.png",
        thumbnail: "./shop ss1.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
        originalClass: "orgImg",
        thumbnailClass: "thumbImg",
      },
      {
        original: "./shop ss2.png",
        thumbnail: "./shop ss2.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
        originalClass: "orgImg",
        thumbnailClass: "thumbImg",
      },
      {
        original: "./shop ss3.png",
        thumbnail: "./shop ss3.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
        originalClass: "orgImg",
        thumbnailClass: "thumbImg",
      },
      {
        original: "./shop ss4.png",
        thumbnail: "./shop ss4.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
        originalClass: "orgImg",
        thumbnailClass: "thumbImg",
      },
      {
        original: "./shop ss5.png",
        thumbnail: "./shop ss5.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
        originalClass: "orgImg",
        thumbnailClass: "thumbImg",
      },
      {
        original: "./shop ss6.png",
        thumbnail: "./shop ss6.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
        originalClass: "orgImg",
        thumbnailClass: "thumbImg",
      },
      {
        original: "./shop ss7.png",
        thumbnail: "./shop ss7.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
        originalClass: "orgImg",
        thumbnailClass: "thumbImg",
      },
      {
        original: "./shop ss8.png",
        thumbnail: "./shop ss8.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
        originalClass: "orgImg",
        thumbnailClass: "thumbImg",
      },
      {
        original: "./shop ss9.png",
        thumbnail: "./shop ss9.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
        originalClass: "orgImg",
        thumbnailClass: "thumbImg",
      },
      {
        original: "./shop ss10.png",
        thumbnail: "./shop ss10.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
        originalClass: "orgImg",
        thumbnailClass: "thumbImg",
      },
      {
        original: "./shop ss11.png",
        thumbnail: "./shop ss11.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
        originalClass: "orgImg",
        thumbnailClass: "thumbImg",
      },
      {
        original: "./shop ss12.png",
        thumbnail: "./shop ss12.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
        originalClass: "orgImg",
        thumbnailClass: "thumbImg",
      },
    ],
    desc: "An ecommerce furniture shop site built with Nextjs, TailwindCSS and Strapi CMS, and used Redux for global state managment",
    ghlink: "https://github.com/Ahmad-Shawish/Furniro-nextjs-strapi",
    tunnel: "https://sqb9npfb-3002.euw.devtunnels.ms/",
  }
];

export const newItemsVanila = [
  {
    id: 1,
    title: "Ecommerce Shop",
    images: {
      img1: "./shop ss1.png",
      img2: "./shop ss2.png",
      img3: "./shop ss3.png",
      img4: "./shop ss4.png",
      img5: "./shop ss5.png",
      img6: "./shop ss6.png",
      img7: "./shop ss7.png",
      img8: "./shop ss8.png",
      img9: "./shop ss9.png",
      img10: "./shop ss10.png",
      img11: "./shop ss11.png",
      img12: "./shop ss12.png",
    },
    desc: "An ecommerce furniture shop site built with Nextjs, TailwindCSS and Strapi CMS, and used Redux for global state managment",
    ghlink: "https://github.com/Ahmad-Shawish/Furniro-nextjs-strapi",
    tunnel: "https://sqb9npfb-3002.euw.devtunnels.ms/",
  }
];

export const newItemsPack2 = [
  {
    id: 1,
    title: "Ecommerce Shop",
    images: [
      "./shop ss1.png",
      "./shop ss2.png",
      "./shop ss3.png",
      "./shop ss4.png",
      "./shop ss5.png",
      "./shop ss6.png",
      "./shop ss7.png",
      "./shop ss8.png",
      "./shop ss9.png",
      "./shop ss10.png",
      "./shop ss11.png",
      "./shop ss12.png",
    ],
    desc: "An ecommerce furniture shop site built with Nextjs, TailwindCSS and Strapi CMS, and used Redux for global state managment",
    ghlink: "https://github.com/Ahmad-Shawish/Furniro-nextjs-strapi",
    tunnel: "https://sqb9npfb-3002.euw.devtunnels.ms/",
  }
];